spring.application.name=codebase-agent

spring.datasource.url=jdbc:postgresql://localhost:5434/codebase_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect




# Gemini

spring.ai.google.genai.embedding.options.model=gemini-embedding-001

spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.embedding.api-key=${spring.ai.google.genai.api-key}
spring.ai.google.genai.project-id=138849535646


spring.ai.vectorstore.pgvector.table-name=code_chunks
spring.ai.vectorstore.pgvector.schema-name=public
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.initialize-schema=false


